### ISSUE TITLE
cleanup source\sass\views\indexpage.scss

### ISSUE THREAD

**Issue by fessehaye** [MozillaFoundation/foundation.mozilla.org#8342] opened 2022-02-26 07:43 UTC
Removing small SASS file and change the classes related to `network-api\networkapi\wagtailpages\templates\wagtailpages\index_page.html`

**Comment by mmmavis** [comment] 2023-06-20 06:30
Closing. Dupe of #8971

**Closed by mmmavis** 2023-06-20 06:30 UTC
Labels: engineering, frontend, code cleanup, SCSS/Tailwind, maintain
