### ISSUE TITLE
Bold styling on Article page not bold enough

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#11898] opened 2024-02-23 15:52 UTC
### Describe the bug
When trying to bold text on [Article](https://foundation.mozilla.org/en/research/library/in-transparency-we-trust/research-report/#our-recommendations) pages, it only slightly bolds the text. On the inspect panel it seems like it's using `font-weight: bolder` when I think it should be `font-weight: bold`. I'm viewing on Firefox.

This is a screenshot of it currently where "Prioritizing machine-readable methods:" should be bold.

<img width="552" alt="Screenshot 2024-02-22 at 5 09 38 PM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/74557207/242a8972-6925-4015-ad96-7b203677f1c1">

### Expected behavior
This is what it's suppose to look like. 

<img width="849" alt="Screenshot 2024-02-23 at 9 41 34 AM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/74557207/632b8aad-134a-49d3-9097-349acc42ff2c">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-80)

**Comment by robdivincenzo** [comment] 2024-03-25 14:56
This is happening because the parent font-weight on articles is actually a light `300`. Elsewhere, the site uses a normal `400` font-weight. Just wanted to double-check that light font-weight rule was intended before I address the bold. Options are:

1) Keep the light font-weight rule and force the bold.

2) Remove the light font-weight rule, and inherit font-weights like other parts of the site.

Here's [option_1](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/3083419/6da32812-5f5f-4556-b848-03ae96b5ba8c) and [option_2](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/3083419/85f029ee-044f-4517-8fac-8711edb7a4b1)

**Comment by kristinashu** [comment] 2024-03-25 22:31
Hi @robdivincenzo, please go with option 1 (keeping the light font-weight). It's a good mental note tho that they are different weights. Thank you for checking!

**Comment by mmmavis** [comment] 2024-05-26 19:30
This has been fixed. Closing.

**Closed by mmmavis** 2024-05-26 19:30 UTC
Labels: bug, engineering, good first bug, p2, needs grooming
