### ISSUE TITLE
Automatic redirects aren't working

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#9961] opened 2023-01-16 17:47 UTC
Redirects should be created automatically when staff move a page or update the slug https://docs.wagtail.org/en/stable/reference/contrib/redirects.html#automatic-redirect-creation however this feature isn't working for us.

@tbrlpld  via [Slack](https://mozilla.slack.com/archives/C04DYP6T6VD/p1673635909640719) 

>  Looks like there is an override in the code base to fix an issue around queryparameters that are being removed during the redirect: https://github.com/wagtail/wagtail/issues/7339. I wonder if that somehow causes the automatic creation of redirects to fail...

### AC
- [x] As an editor, redirects should happen automatically when I update a slug or move a page in the CMS (as described in https://docs.wagtail.org/en/stable/reference/contrib/redirects.html#automatic-redirect-creation)

## Dev tasks: 

[Timeboxed to half a day]

1. Create a unit test to change page slugs
2. Investigate why redirects are not automatically created
3. Create a unit test to move the page 
4. Investigate why redirects are not automatically updated

**Comment by kevinhowbrook** [comment] 2023-01-24 09:52
Evidence that this should work with the current version https://docs.wagtail.org/en/latest/reference/contrib/redirects.html#automatic-redirect-creation

**Comment by kevinhowbrook** [comment] 2023-01-27 15:29
Initial local testing, redirects are created when moving a page via the UI

**Comment by tbrlpld** [comment] 2023-01-27 16:14
Does it work on staging and locally with staging/prod data?

**Comment by kevinhowbrook** [comment] 2023-01-27 16:27
> Does it work on staging and locally with staging/prod data?

That's my next port of call. Just pushing a valid test up

**Comment by kevinhowbrook** [comment] 2023-01-30 16:31
Next test to write - include multisites in current tests

**Comment by kevinhowbrook** [comment] 2023-02-02 11:41
@tbrlpld - would be good to get your eyes on the tests so far - I've tried to create tests that should fail with what we are seeing happen. I'm a bit stumped right now as they are all passing. I'm starting to scrape the barrel a bit with what this issue could be.

**Comment by tbrlpld** [comment] 2023-02-03 00:00
@kevinhowbrook @kristinashu I have just tested this on staging (by changing a page's slug) and it looks like the redirects are being created. But, the redirects don't take effect. 

* https://foundation.mofostaging.net/en/top-banner/child-banner/ should redirect to https://foundation.mofostaging.net/en/top-banner/child-banner-new-slug/ but does not
* The redirect however does exist: https://foundation.mofostaging.net/cms/redirects/?q=child (even for all locales)

So it does look like some catch all URL config is serving before the Wagtail redirect handling is taking effect.

**Comment by kevinhowbrook** [comment] 2023-02-03 10:49
I think this might be the reason then https://github.com/mozilla/foundation.mozilla.org/blob/e25670341bc97b2f65bb5d16251a78df66500097/network-api/networkapi/wagtailcustomization/redirects/middleware.py#L11

**Comment by kevinhowbrook** [comment] 2023-02-03 13:46
It would seem that the following is occurring in this middleware:

If the request path has a  lang code, remove it.
e.g /en/test-page becomes /test-page

Then we check _original_get_redirect and since there isn't a path record for /test-page, this is returning None, so redirect isn't delivered because one isn't found

**Comment by tbrlpld** [comment] 2023-02-03 15:12
Why would we want to remove the language code in the redirect? All the redirects have language codes. 🤔

**Comment by tbrlpld** [comment] 2023-02-03 15:13
The only think I can see is that if there is no language code in the redirect, you want to make sure we add the default one... but that does not seem to be what it does.

**Comment by kevinhowbrook** [comment] 2023-02-03 15:32
> Why would we want to remove the language code in the redirect? All the redirects have language codes. thinking

Yea this is why I'm a bit confused :rofl:

**Comment by cdanfon** [comment] 2023-02-06 18:59
Next steps: 

- Code to be reviewed by @tbrlpld

**Comment by kevinhowbrook** [comment] 2023-03-10 09:48
I've improved the tests here so I think this is good for a re-review, have assigned @tbrlpld

**Comment by kevinhowbrook** [comment] 2023-04-28 12:26
Just another update on this - I have created a management command to fix redirects after we set this live. I've asked tibor to re-review it.

Should all be well, we should deploy the PR to staging and run the command to ensure redirects are created.

**Comment by kevinhowbrook** [comment] 2023-05-04 13:41
PR [here](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/10065) has been reviewed and we are in a good place to merge and test this on staging.

After merging, we will need to run the management command `fix_redirects`.

**Comment by kristinashu** [comment] 2023-05-30 14:03
@kevinhowbrook @mtdenton do you know if this got merged and tested?

**Comment by mtdenton** [comment] 2023-05-30 18:14
Looks like the percy checks were never done here, adding the tag

**Comment by kevinhowbrook** [comment] 2023-06-01 05:58
> @kevinhowbrook @mtdenton do you know if this got merged and tested?

Hey, no the PR is still open and ready to merge for testing https://github.com/MozillaFoundation/foundation.mozilla.org/pull/10065

**Comment by kristinashu** [comment] 2023-06-05 17:27
@jhonatan-lopes has offered to have a look at this, thank you!

**Comment by jhonatan-lopes** [comment] 2023-06-07 12:19
PR has been merged and `fix_redirects` command has been run in staging. @kristinashu to test it on staging to confirm if redirects are working again.

**Comment by kristinashu** [comment] 2023-06-07 15:35
@jhonatan-lopes yay this is working well and is ready for prod!

I test updating the slug and moving pages and they worked as expected. I also tested different languages, the main foundation site as well as mozfest and PNI and they all worked.

**Comment by mtdenton** [comment] 2023-06-20 16:04
Reopening this, we had a regression with a push last week. Should be closed today

**Closed** 2023-06-23 11:40 UTC
Labels: bug, engineering, support
