### ISSUE TITLE
Wagtail Upgrade | Preview not available on page editor

### ISSUE THREAD

**Issue by cdanfon** [MozillaFoundation/foundation.mozilla.org#10380] opened 2023-03-27 12:37 UTC
Wagtail 4.1 comes with an inline preview on the page editor that's currently not displaying, see below:

![Preview-not-working.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/7c29d435-fd33-4ce4-8ab3-c18355a9a868)

In the past, (ie Wagtail v3.0 I've experienced that when trying to preview a page sometimes the site would through 500 errors, wondering if this has anything to do with it).

**Comment by kevinhowbrook** [comment] 2023-03-27 13:50
Thanks @cdanfon 

I think this is CSP issue. These are set via environment variables. I'm not sure of the set up on staging and prod but locally we have the following:

```
CSP_FRAME_ANCESTORS=" 'none' "
```

I think this env var will need updating on the staging and production instances to:

```
CSP_FRAME_ANCESTORS=" 'self' "
```

This is because the preview is now loaded in an iframe in the browser, and it looks like we have configured the site to not be able to do that.

**Comment by cdanfon** [comment] 2023-03-27 14:08
Thanks @kevinhowbrook Could updating that env var change create any issues?

**Comment by kristinashu** [comment] 2023-03-27 17:27
Preview seems to be working well for me (it's a pretty amazing feature!)

**Comment by cdanfon** [comment] 2023-03-28 11:24
Looking good on my side too, thanks @mtdenton

**Comment by cdanfon** [comment] 2023-03-28 11:25
I'll close this ticket once we've deployed to prod and update env var there too

**Comment by danielfmiranda** [comment] 2023-03-29 15:42
Hi @cdanfon! I updated the CSP variables on prod, and Kristina confirmed that the preview feature is now working. Going to close this ticket 👍

**Closed by danielfmiranda** 2023-03-29 15:42 UTC
Labels: bug 🦠, Wagtail 4.1.3
