### ISSUE TITLE
Add Video Block to Accordion Block

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/foundation.mozilla.org#10467] opened 2023-04-06 22:44 UTC
Add the video block to the accordion block so that editors can feature videos in accordions.

## Acceptance Criteria:
- On any wagtail page that supports Accordions ...
    - as an editor ...
       - [x] I can add a video block to be featured in an accordion
     - as a visitor ...
         - [x] I can see a video block featured in an accordion

**Comment by mmmavis** [comment] 2023-04-12 22:15
Took this on because I have some bandwidth today. PR on the way.

**Comment by mmmavis** [comment] 2023-04-17 16:27
I hit errors when I QA'ed it on staging. I'm gonna investigate to see where they were coming from. Will give updates when I find out more.

**Comment by mmmavis** [comment] 2023-04-18 00:57
Hi @beccaklam , it was easy to enable the video block to be part of the accordion block. I basically only had to turn on the toggle in backend. However, when I tested it on different page types the results seemed to be unpredirctable in terms of the width of the video (e.g., on some page types, the "full width" version is smaller than "wide" version). Please see screenshots below. 

I wanted to check with you to see if we are good with landing this as is tomorrow and fix the inconsitent styling issue as follow-up? It will take some time to find a proper solution for the styling issue because all pages are using the same template code for video. To add in more complexity, each page type is structured differently and have different width constrains. We need to be extra careful so we don't introduce regressions. To find a proper solution, we'll need to 

1. Visual regression testing: add video block to pages that allow video block
   - add both the "within accordion" version and the "standalone" version
   - for each version, include the three width type: normal, wide, full width
2. Once we include all possible variations to visual regression tests, we then can safely make code changes without worrying about breaking existing styling. Finding a solution can still take time, but at least we won't accidently introduce regressions.

Please let me know what approach you prefer. If we prefer landing everything in one go, I'll revert the code changes I merged in last week. Either way I'll create a ticket for updating our visual regression tests to include video block.


## Screencaps
- [Primary page](https://user-images.githubusercontent.com/2896608/232636773-f29866cf-9849-4a1c-9471-39343fa1a9d2.png)
- [Blog page](https://user-images.githubusercontent.com/2896608/232636894-1da2d114-4c80-47a9-8a03-7436e86b2a6a.png)
- [Article page](https://user-images.githubusercontent.com/2896608/232637094-430c0529-b25d-45f6-badd-2914cf58ac93.png)
- [Campaign page](https://user-images.githubusercontent.com/2896608/232636951-b2663e85-fe39-44ea-a963-e640c71272bf.png)

**Comment by beccaklam** [comment] 2023-04-18 14:28
Hi @mmmavis thanks for flagging this. I'm okay landing this as is and fixing the inconsistent styling issue in the future!

**Comment by mmmavis** [comment] 2023-04-18 16:22
@beccaklam Awesome! I'll move forward with this approach. Thanks!

**Comment by mmmavis** [comment] 2023-04-18 16:27
Hi @beccaklam forgot to ask you to QA the work on staging. 

- https://foundation.mofostaging.net/cms/pages/22900/edit/
- https://foundation.mofostaging.net/en/blog/how-to-tell-chat-gpt-generated-text/ (look for "This is the title of the accordion" at the beginning of the article)

Feel free to use another page to test! Thanks!

**Comment by beccaklam** [comment] 2023-04-18 21:34
Hi @mmmavis this looks good to me. Approved! ✅

**Closed** 2023-04-19 20:18 UTC
Labels: engineering, RCC, improvement

**Comment by mmmavis** [comment] 2023-04-19 21:15
Follow-up ticket created: https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10512
