### ISSUE TITLE
PNI related products aren't updating and are in wrong order

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/foundation.mozilla.org#11799] opened 2024-01-31 20:24 UTC
### Describe the bug
Updating a related product on PNI does not update. The related products also don't appear in the order they were chosen (less of a priority to fix).

### To Reproduce
1. Go to a PNI product page https://foundation.mofostaging.net/cms/pages/24784/edit/ 
2. Update on of the Related Products
3. Look at side preview or click on Preview and see the error that the preview doesn't update

<img width="1320" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/b6d8ed8d-a5a3-4984-aba0-ab527ab42db6">

### Expected behavior
The product should update and be in the correct order. Note that I believe it shows the right products once the page has been published (but the order is still wrong).

cc @jhonatan-lopes

**Comment by danielfmiranda** [comment] 2024-02-01 19:33
Hi @kristinashu!

The fix for this issue has now been merged and is live on staging. I have tested it out on https://foundation.mofostaging.net/en/privacynotincluded/dodge/ and it seems to be working, but do you think you could please take a look whenever you have a free moment and leave a comment if everything is working as expected?

Thanks!

**Comment by kristinashu** [comment] 2024-02-06 20:34
Hi @danielfmiranda, I tried it a couple times on staging but I'm still seeing the same issue. I both reordered and replaced a project but the preview (side preview and the full preview) still shows the original products and order. It shows the right order and products once I publish the page but not in the preview.

 <img width="1090" alt="Screenshot 2024-02-06 at 12 30 56 PM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1068783/95e451b6-ec6c-40cb-8bd2-0969bab1d2c1">

**Comment by danielfmiranda** [comment] 2024-02-06 22:20
Apologies @kristinashu! It appears I misread this ticket and while the PR #11800 ensures that the products render in the order they are set through the CMS, it does not provide a fix for the preview mode not working.

The reason the preview mode is not working is because the "related product" relationships are not created until a user publishes the page. 

To investigate this issue, I have created #11835 and will work on it as part of this sprints support duty!

@jhonatan-lopes  just curious, are there any wagtail hooks you can think of that we can tap into in order to make sure that related product changes are rendered in the preview window?

**Comment by jhonatan-lopes** [comment] 2024-02-07 12:39
Hey @danielfmiranda, I think you're right, the relationships won't be updated until they are saved to the database. By publishing the page and then re-editing, we can see that the relationships will be ordered properly, so that might indeed be the issue.

On a Wagtail's edit page, none of the foreign keys/related models are actually saved to the database until we make a post request. We make use of [`django-modelcluster`](https://github.com/wagtail/django-modelcluster) to keep track of the relationships on memory until we're ready to make a post request and properly save them on the database. That's why we use `ParentalKey`s instead of `ForeignKey`s sometimes.

The rendering here is done by the `localized_related_products`, which we changed to reduce the number of DB queries and do the localisation on the server side. The problem is that when we make a request to a `ProductPage` in preview mode, the changes that were made by the editor are not reflected on the DB (remember, they are only in-memory so far), so calling `localized_related_products` on the `ProductPage` instance will return what is in the database, i.e. the related products from the last change, not what the editor is seeing.

I'll do some research to see if we can "fudge" this request and detect that we are on preview mode. If so, we could bypass the localisation and query the products directly.

**Comment by danielfmiranda** [comment] 2024-02-20 19:31
Jhonatan and I just confirmed that this is working as expected on staging. Moving to "Ready for prod" now!

**Closed** 2024-02-23 00:35 UTC
Labels: bug, engineering, buyer's guide 🛍
