### ISSUE TITLE
Altered spacing between blocks on Mozfest Website

### ISSUE THREAD

**Issue by data-sync-user** [MozillaFoundation/foundation.mozilla.org#12315] opened 2024-05-09 13:22 UTC
### Describe the bug
This is a report submitted by Marc, stating that the Mozfest website went through a recent change that altered spacing between blocks. This is causing quite a few issues where they are not able to align buttons and other pieces of content together.

He believes that the PR that might have impacted this work was this one:
[https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11862](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11862|smart-link) 

He is requesting if we could revert to how things work before.

### Expected behavior
Users should be able to align content as before.

### Screenshots
!Screenshot 2024-04-17 at 15.25.06.png|width=910,height=524,alt="Screenshot 2024-04-17 at 15.25.06.png"!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP1-632)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/62698">Screenshot 2024-04-17 at 15.25.06.png</a>

**Comment by robdivincenzo** [comment] 2024-05-23 12:05
Hey @marcwalsh! Here's what I found from investigating. #11862 does not appear to affect spacing on this element, but I have some more info on what this used to look like.

In 2022, the element looked like this:
<img width="1177" alt="2022" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/3083419/d2a51ded-7980-42d2-8d2d-1a79227a8f6d">

It was redesigned in 2023 to look like this:
<img width="1215" alt="2023" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/3083419/6650ffd0-8bd0-42d5-9373-ce6b5b729b72">

And sometime later a line divider was added so that now it looks like this:
<img width="1155" alt="2024" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/3083419/eb30c53c-8436-4430-934b-d5739e7fc712">

I have two suggestions:

Option 1 would be to remove the line divider. This is simply a CMS edit and would make spacing like it used to.
<img width="1202" alt="current_no-divider" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/3083419/649e9410-0cb4-4d25-ad09-d0773e146ed9">

Option 2 is to shorten the spacing of the element. This would require a styling change. Could potentially affect other pages using that element so we'd have to review for regressions.
<img width="1200" alt="2022_spacing_divider" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/3083419/eb45ceef-4c93-4943-af16-341654ed8930">

Do any of these options seem what you we're looking for? Or do you have any other info on how the page layout needs to look?

**Comment by marcwalsh** [comment] 2024-05-23 12:26
Thanks @robdivincenzo - option 2 feels like it would be better, as there isn't additional spacing adding there. 

There's a horizontal line that we added as a break, but that has the same spacing above and below it, but the issue we're facing is that the built in spacing of the blocks is causing the spacing issues.

We're seeing this on the top of the Songs of the Living page as well: https://www.mozillafestival.org/en/songs-of-the-living/ and that's using a different block.

It seems like different combinations of specific blocks cause this issue - it would be great to solve it on the whole, to avoid battling with it whenever designing a page.

**Comment by robdivincenzo** [comment] 2024-05-24 15:53
Thanks for the additional info Marc! @kristinashu any design comments on the spacing adjustment of these two blocks? The `Image Feature` is a global block used on 7 other live non-mozfest pages. I have a list of those ready on a review app so you can see the impact of the change:

- https://foundation-s-tp1-632-12-cj9per.mofostaging.net/en/what-we-fund/fellowships/fellows-for-tech-and-society/program-design/
- https://foundation-s-tp1-632-12-cj9per.mofostaging.net/en/what-we-fund/fellowships/fellows-for-tech-and-society/call-for-proposals/information-session/
- https://foundation-s-tp1-632-12-cj9per.mofostaging.net/en/campaigns/tiktok-reporter-app/
- https://foundation-s-tp1-632-12-cj9per.mofostaging.net/en/data-futures-lab/resources/
- https://foundation-s-tp1-632-12-cj9per.mofostaging.net/en/data-futures-lab/events/
- https://foundation-s-tp1-632-12-cj9per.mofostaging.net/en/responsible-computing-challenge/industry-support/
- https://foundation-s-tp1-632-12-cj9per.mofostaging.net/en/docs/how-do-i-wagtail/blocks-types/

As for the second block mentioned on the Songs of the Living page, it is specific to mozfest, and here is an example of that adjustment from my local copy:

**Before:**

![Screenshot 2024-05-24 at 11 43 29 AM](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/3083419/3dfbec4e-12b3-43d2-87a3-81f53a7a773a)

**After:**

![Screenshot 2024-05-24 at 11 41 25 AM](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/3083419/a8990a1e-da08-4b91-9da4-fb6ef42251b8)

**Comment by robdivincenzo** [comment] 2024-06-03 15:50
Hey @marcwalsh- want to try to get this in for deployment tomorrow if possible, but have one more point to discuss.

Reverting the auto-spacer will re-introduce the tight spacing that #11756 adjusted (for better and for worse). Here are screenshots of what before and after will look like:

Before Revert:
<img width="1352" alt="Screenshot 2024-06-03 at 11 20 18 AM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/3083419/216bc053-972e-4ff0-be2e-4025630dc85d">

After Revert:
<img width="1346" alt="Screenshot 2024-06-03 at 11 20 24 AM" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/3083419/09a443af-e7d2-43b8-b47a-5af5900ef58b">

This solution is currently ready to go. We would coordinate a deployment with you so you're available to insert the spacer where needed when this goes live. Wanted to double-check if this approach works for you.

If you're unavailable or that approach doesn't work, I have an alternative idea to keep the site looking the same post-deployment. However, it's a much more complex deployment, requires further testing, and still requires manual editing to get the pages how you want them to look.

**Comment by marcwalsh** [comment] 2024-06-03 16:16
Thanks @robdivincenzo - happy to sync on deployment for this for sure. Let me know a rough date and time.

**Comment by robdivincenzo** [comment] 2024-06-04 06:18
Awesome, thanks @marcwalsh! The changes are all merged in and ready on [staging](https://mozillafestival.mofostaging.net/en/). Feel free to login, and test adding the spacer, etc.

We usually deploy on Tuesdays, so today will work for me. I can schedule one for EST morning if that's good for your timezone and gives you enough time to review / get set. Maybe around 10 a.m. EST?

**Closed** 2024-06-25 14:45 UTC
Labels: design
