### ISSUE TITLE
French PNI product pages are crashing

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#11394] opened 2023-11-09 10:08 UTC
Hi,

I noticed many (maybe all) of the PNI products translated in French are crashing, for instance the Nintendo Switch. Syncing translations has fixed the issue, but sharing the error it raised below. It seem to affect only French.

Here’s another affected product that I didn’t fix, to help with investigating the issue: https://foundation.mozilla.org/fr/privacynotincluded/slack/

If there’s no easy fix for this, I might need help from an admin to go through all the PNI products and individually sync the translations

```
2023-11-09T09:54:01.372305+00:00 heroku[router]: at=info method=GET path="/fr/privacynotincluded/nintendo-switch/" host=foundation.mozilla.org request_id=159cac2e-9035-4726-a556-bd6939d550ea fwd="83.113.14.218,172.71.134.37" dyno=web.5 connect=0ms service=1160ms status=500 bytes=3158 protocol=https

2023-11-09T09:54:01.358881+00:00 app[web.5]: Internal Server Error: /fr/privacynotincluded/nintendo-switch/

2023-11-09T09:54:01.358891+00:00 app[web.5]: Traceback (most recent call last):

2023-11-09T09:54:01.358894+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 829, in _resolve_lookup

2023-11-09T09:54:01.358895+00:00 app[web.5]:     current = current[bit]

2023-11-09T09:54:01.358895+00:00 app[web.5]: TypeError: 'GeneralProductPage' object is not subscriptable

2023-11-09T09:54:01.358897+00:00 app[web.5]: 

2023-11-09T09:54:01.358897+00:00 app[web.5]: During handling of the above exception, another exception occurred:

2023-11-09T09:54:01.358898+00:00 app[web.5]: 

2023-11-09T09:54:01.358898+00:00 app[web.5]: Traceback (most recent call last):

2023-11-09T09:54:01.358898+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner

2023-11-09T09:54:01.358898+00:00 app[web.5]:     response = get_response(request)

2023-11-09T09:54:01.358899+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response

2023-11-09T09:54:01.358899+00:00 app[web.5]:     response = response.render()

2023-11-09T09:54:01.358901+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render

2023-11-09T09:54:01.358901+00:00 app[web.5]:     return old_render(self)

2023-11-09T09:54:01.358901+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/response.py", line 105, in render

2023-11-09T09:54:01.358901+00:00 app[web.5]:     self.content = self.rendered_content

2023-11-09T09:54:01.358902+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content

2023-11-09T09:54:01.358902+00:00 app[web.5]:     return real_rendered_content.fget(self)

2023-11-09T09:54:01.358902+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/response.py", line 83, in rendered_content

2023-11-09T09:54:01.358902+00:00 app[web.5]:     return template.render(context, self._request)

2023-11-09T09:54:01.358902+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render

2023-11-09T09:54:01.358902+00:00 app[web.5]:     return self.template.render(context)

2023-11-09T09:54:01.358902+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/scout_apm/core/stacktracer.py", line 25, in wrapper

2023-11-09T09:54:01.358902+00:00 app[web.5]:     return wrapped(*args, **kwargs)

2023-11-09T09:54:01.358903+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 170, in render

2023-11-09T09:54:01.358903+00:00 app[web.5]:     return self._render(context)

2023-11-09T09:54:01.358903+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 162, in _render

2023-11-09T09:54:01.358903+00:00 app[web.5]:     return self.nodelist.render(context)

2023-11-09T09:54:01.358903+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 938, in render

2023-11-09T09:54:01.358903+00:00 app[web.5]:     bit = node.render_annotated(context)

2023-11-09T09:54:01.358903+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated

2023-11-09T09:54:01.358903+00:00 app[web.5]:     return self.render(context)

2023-11-09T09:54:01.358904+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/pattern_library/loader_tags.py", line 38, in render

2023-11-09T09:54:01.358904+00:00 app[web.5]:     return super().render(context)

2023-11-09T09:54:01.358904+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render

2023-11-09T09:54:01.358904+00:00 app[web.5]:     return compiled_parent._render(context)

2023-11-09T09:54:01.358904+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 162, in _render

2023-11-09T09:54:01.358904+00:00 app[web.5]:     return self.nodelist.render(context)

2023-11-09T09:54:01.358904+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 938, in render

2023-11-09T09:54:01.358904+00:00 app[web.5]:     bit = node.render_annotated(context)

2023-11-09T09:54:01.358904+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated

2023-11-09T09:54:01.358904+00:00 app[web.5]:     return self.render(context)

2023-11-09T09:54:01.358904+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/pattern_library/loader_tags.py", line 38, in render

2023-11-09T09:54:01.358904+00:00 app[web.5]:     return super().render(context)

2023-11-09T09:54:01.358905+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render

2023-11-09T09:54:01.358905+00:00 app[web.5]:     return compiled_parent._render(context)

2023-11-09T09:54:01.358905+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 162, in _render

2023-11-09T09:54:01.358905+00:00 app[web.5]:     return self.nodelist.render(context)

2023-11-09T09:54:01.358905+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 938, in render

2023-11-09T09:54:01.358905+00:00 app[web.5]:     bit = node.render_annotated(context)

2023-11-09T09:54:01.358905+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated

2023-11-09T09:54:01.358905+00:00 app[web.5]:     return self.render(context)

2023-11-09T09:54:01.358905+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/scout_apm/core/stacktracer.py", line 25, in wrapper

2023-11-09T09:54:01.358905+00:00 app[web.5]:     return wrapped(*args, **kwargs)

2023-11-09T09:54:01.358906+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render

2023-11-09T09:54:01.358906+00:00 app[web.5]:     result = block.nodelist.render(context)

2023-11-09T09:54:01.358906+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 938, in render

2023-11-09T09:54:01.358908+00:00 app[web.5]:     bit = node.render_annotated(context)

2023-11-09T09:54:01.358908+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated

2023-11-09T09:54:01.358908+00:00 app[web.5]:     return self.render(context)

2023-11-09T09:54:01.358908+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/scout_apm/core/stacktracer.py", line 25, in wrapper

2023-11-09T09:54:01.358909+00:00 app[web.5]:     return wrapped(*args, **kwargs)

2023-11-09T09:54:01.358909+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render

2023-11-09T09:54:01.358909+00:00 app[web.5]:     result = block.nodelist.render(context)

2023-11-09T09:54:01.358909+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 938, in render

2023-11-09T09:54:01.358909+00:00 app[web.5]:     bit = node.render_annotated(context)

2023-11-09T09:54:01.358909+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated

2023-11-09T09:54:01.358909+00:00 app[web.5]:     return self.render(context)

2023-11-09T09:54:01.358909+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/defaulttags.py", line 519, in render

2023-11-09T09:54:01.358909+00:00 app[web.5]:     return self.nodelist.render(context)

2023-11-09T09:54:01.358909+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 938, in render

2023-11-09T09:54:01.358910+00:00 app[web.5]:     bit = node.render_annotated(context)

2023-11-09T09:54:01.358910+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated

2023-11-09T09:54:01.358910+00:00 app[web.5]:     return self.render(context)

2023-11-09T09:54:01.358910+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/pattern_library/loader_tags.py", line 90, in render

2023-11-09T09:54:01.358910+00:00 app[web.5]:     return super().render(context)

2023-11-09T09:54:01.358910+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/loader_tags.py", line 195, in render

2023-11-09T09:54:01.358910+00:00 app[web.5]:     return template.render(context)

2023-11-09T09:54:01.358910+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/scout_apm/core/stacktracer.py", line 25, in wrapper

2023-11-09T09:54:01.358910+00:00 app[web.5]:     return wrapped(*args, **kwargs)

2023-11-09T09:54:01.358910+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 172, in render

2023-11-09T09:54:01.358910+00:00 app[web.5]:     return self._render(context)

2023-11-09T09:54:01.358911+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 162, in _render

2023-11-09T09:54:01.358911+00:00 app[web.5]:     return self.nodelist.render(context)

2023-11-09T09:54:01.358911+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 938, in render

2023-11-09T09:54:01.358911+00:00 app[web.5]:     bit = node.render_annotated(context)

2023-11-09T09:54:01.358911+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated

2023-11-09T09:54:01.358911+00:00 app[web.5]:     return self.render(context)

2023-11-09T09:54:01.358912+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/pattern_library/loader_tags.py", line 90, in render

2023-11-09T09:54:01.358912+00:00 app[web.5]:     return super().render(context)

2023-11-09T09:54:01.358912+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/loader_tags.py", line 195, in render

2023-11-09T09:54:01.358912+00:00 app[web.5]:     return template.render(context)

2023-11-09T09:54:01.358913+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/scout_apm/core/stacktracer.py", line 25, in wrapper

2023-11-09T09:54:01.358913+00:00 app[web.5]:     return wrapped(*args, **kwargs)

2023-11-09T09:54:01.358913+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 172, in render

2023-11-09T09:54:01.358913+00:00 app[web.5]:     return self._render(context)

2023-11-09T09:54:01.358913+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 162, in _render

2023-11-09T09:54:01.358913+00:00 app[web.5]:     return self.nodelist.render(context)

2023-11-09T09:54:01.358914+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 938, in render

2023-11-09T09:54:01.358914+00:00 app[web.5]:     bit = node.render_annotated(context)

2023-11-09T09:54:01.358914+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated

2023-11-09T09:54:01.358914+00:00 app[web.5]:     return self.render(context)

2023-11-09T09:54:01.358914+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/defaulttags.py", line 517, in render

2023-11-09T09:54:01.358915+00:00 app[web.5]:     values = {key: val.resolve(context) for key, val in self.extra_context.items()}

2023-11-09T09:54:01.358915+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/defaulttags.py", line 517, in <dictcomp>

2023-11-09T09:54:01.358915+00:00 app[web.5]:     values = {key: val.resolve(context) for key, val in self.extra_context.items()}

2023-11-09T09:54:01.358915+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 671, in resolve

2023-11-09T09:54:01.358915+00:00 app[web.5]:     obj = self.var.resolve(context)

2023-11-09T09:54:01.358915+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 796, in resolve

2023-11-09T09:54:01.358915+00:00 app[web.5]:     value = self._resolve_lookup(context)

2023-11-09T09:54:01.358916+00:00 app[web.5]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 837, in _resolve_lookup

2023-11-09T09:54:01.358916+00:00 app[web.5]:     current = getattr(current, bit)

2023-11-09T09:54:01.358917+00:00 app[web.5]:   File "/app/network-api/networkapi/wagtailpages/pagemodels/buyersguide/products.py", line 784, in average_bin

2023-11-09T09:54:01.358918+00:00 app[web.5]:     return self.annotated_evaluation.average_bin

2023-11-09T09:54:01.358918+00:00 app[web.5]: AttributeError: 'NoneType' object has no attribute 'average_bin'
```

**Comment by jhonatan-lopes** [comment] 2023-11-09 13:21
Fixed by manually copying the `evaluation` object from the English source. Left over from #11347

Hey @TheoChevalier, was there anything that triggered this? Were these copied last week or anything like that?

**Comment by TheoChevalier** [comment] 2023-11-09 15:00
> Fixed by manually copying the `evaluation` object from the English source. Left over from #11347
> 
> Hey @TheoChevalier, was there anything that triggered this? Were these copied last week or anything like that?

@jhonatan-lopes Now that I’m thinking about it, I ran a search & replace in Pontoon yesterday on all French translations, and that resulted in Pontoon bumping the "Po-revision-date" for all files https://github.com/mozilla-l10n/fomo-content/commit/5eb17ab0d89fbf9aa120c83184994a179c55acbc
Then I think that triggered Wagtail-localize to try and publish all those pages, even if the only change was the revision date.

**Comment by jhonatan-lopes** [comment] 2023-11-09 15:04
Thanks @TheoChevalier, that's very helpful to know. The reason I asked is that we do have some post-save/post-copy hooks to create evaluation objects when product pages are copied or created.

It seems then that this particular scenario is interfering with that, maybe... possibly related to the `wagtail-localize` publication (although the evaluation should sync with the source page). I'll investigate further.

**Comment by jhonatan-lopes** [comment] 2023-11-09 19:18
We've figured out the root cause of the issue. Let's track this on the more general #11400.

**Closed by jhonatan-lopes** 2023-11-09 19:18 UTC
Labels: bug, engineering, needs grooming
