### ISSUE TITLE
Related topics box is missing on localized blog index pages

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#9101] opened 2022-07-14 13:16 UTC
When the index blog page is localized (i.e is not just an alias page), the related topics box is missing.

English:
<img width="1191" alt="Capture d’écran 2022-07-14 à 14 45 46" src="https://user-images.githubusercontent.com/1294206/178990767-f188b172-b426-418d-9e73-e65da132cb2f.png">

French:

<img width="1224" alt="Capture d’écran 2022-07-14 à 14 44 18" src="https://user-images.githubusercontent.com/1294206/178990795-1f7ebc95-fccd-4bb7-9296-bacba3eac234.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-299)

**Comment by jhonatan-lopes** [comment] 2023-07-26 12:38
Cannot reproduce. The box is showing up in production:

![image.png](https://images.zenhubusercontent.com/642ac2a58baa9705f8108262/3e01ddaf-1379-4988-a602-618276408797)

![image.png](https://images.zenhubusercontent.com/642ac2a58baa9705f8108262/e95ece69-c8c8-4ccd-9561-0270b6723c60)

**Comment by jhonatan-lopes** [comment] 2023-07-26 13:32
@TheoChevalier thanks for the additional info, I'll try to replicate it again

**Comment by jhonatan-lopes** [comment] 2023-07-26 14:19
Sorry @TheoChevalier, no luck so far. I've updated the name on **Advocacy** and **Common Voice** to **[EN] Advocacy** and **[EN] Common Voice** and then synced the changes. For **[EN] Advocacy**, I've translated the name to **[FR} Advocacy**, but left the **[EN] Common Voice** without a name translation (which should fall back to the English name).

The behaviour is as expected:

![image.png](https://images.zenhubusercontent.com/642ac2a58baa9705f8108262/4acfcc57-ebfb-4d05-9894-96f7361cb3a1)

It shows the *Related Topics* box, *Advocacy* is showing the translated French name, and *Common Voice* falls back to the default English name.

Are you able to replicate the bug on Staging?

**Comment by TheoChevalier** [comment] 2023-07-26 15:13
@jhonatan-lopes Actually, it’s changes to the Blog home page that aren’t synced. 

For instance, I’ve removed the "Internet Health" category and added "Moz News Beat", then synced the change to translated pages (https://foundation.mofostaging.net/cms/localize/update/17/?next=%2Fcms%2Fpages%2F46%2F) and that isn’t reflected on translated pages:


<img width="386" alt="Capture d’écran 2023-07-26 à 17 12 15" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1294206/a05d48fa-dc08-474b-82cd-78026fa883f5">

<img width="388" alt="Capture d’écran 2023-07-26 à 17 12 04" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1294206/f3cf2579-1945-4d6c-a0a4-1a7a4a79dbcd">

**Comment by jhonatan-lopes** [comment] 2023-07-27 11:20
Thanks for the extra info @TheoChevalier! I was able to reproduce the bug now. I'll continue to investigate it

**Comment by danielfmiranda** [comment] 2024-05-14 23:41
Closing this issue, as the fix has been pushed to prod via #12235

**Closed by danielfmiranda** 2024-05-14 23:41 UTC
Labels: bug, engineering, localization 🌎, p1
