### ISSUE TITLE
[PNI Privacy Index] Finalize webpage design

### ISSUE THREAD

**Issue by nancyt1** [MozillaFoundation/foundation.mozilla.org#10953] opened 2023-08-01 22:52 UTC
- [ ] Get approval from stakeholders and Mavis
- [ ] Prep file for handoff

**Comment by kristinashu** [comment] 2023-09-07 20:55
A duplicate of this was made https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11072!

**Closed by kristinashu** 2023-09-07 20:55 UTC
Labels: design, buyer's guide 🛍
