### ISSUE TITLE
Refresh our maintenance page

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/foundation.mozilla.org#11535] opened 2023-12-12 17:47 UTC
This is how our maintenance page looks like:

![Screenshot 2023-12-12 at 09-44-03 Mozilla Foundation - Under Maintenance](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/79c26116-8870-4bd5-b7ac-395ef2ca1308)

### Areas to update
* clean up broken code
* fix/remove broken links (links on fo.mo won't work when the site is down)
* fix styling or design if needed

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-220)

**Comment by mtdenton** [comment] 2023-12-12 18:02
This is statically hosted on S3, correct? We'll need to investigate how to deploy this as well, but it shouldn't be too difficult.

**Comment by mmmavis** [comment] 2023-12-12 18:04
Yea I believe it's on S3 and deployed via GitHub action: https://github.com/MozillaFoundation/foundation.mozilla.org/actions/workflows/maintenance-page.yml

**Comment by data-sync-user** [comment] 2024-06-21 16:25
➤ Simon Acosta Torres commented:

Tyler Denton Not a priority because Mavis was handling this work, but if we still want to do this, we could assign to Ram. We would just need that S3 URL for quick access on here for reference.

**Comment by data-sync-user** [comment] 2024-08-12 21:32
➤ Simon Acosta Torres commented:

Closing as this is a duplicate of https://mozilla-hub.atlassian.net/browse/TP1-315 ( https://mozilla-hub.atlassian.net/browse/TP1-315|smart-link ) /.

**Closed** 2024-08-13 18:15 UTC
Labels: design, needs discussion, engineering, p2, maintain, needs grooming
